### ISSUE TITLE
bring under Gratipay org?

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/gratipay-badge#5]
@twolfson Would you be interested in bringing this project under the Gratipay organization on GitHub? I'd be happy to keep you as the manager of the repo from a permissions standpoint. :-)

**Comment by twolfson** [comment]
I would definitely be up for that. Let's first address #3 and #4, then we can sort the rest out.

**Comment by chadwhitacre** [comment]
Sounds good! :-)

**Comment by twolfson** [comment]
Okay, #3 and #4 have been closed up. I have been going back and forth on whether we should do a rename or fork based on `git` history (e.g. create repo, push `master`, reset CHANGELOG).

I am leaning towards the latter since it will allow us to throw away things like `dist/gittip.png` because some people hotlinked to `master` (e.g. me). Thoughts?

**Comment by seanlinsley** [comment]
> I have been going back and forth on whether we should do a rename or fork based on git history (e.g. create repo, push master, reset CHANGELOG).

I'm not sure I understand the fork option. What downside is there to renaming the repo to `gratipay-badge` and moving it under the Gratipay organization?

**Comment by twolfson** [comment]
The fork option would go as follows:
- Create new repository `gratipay/grapitay-badge`
- Push `twolfson/gittip-badge` history into repository
- Deprecate `twolfson/gittip-badge` with note in README

From the command line, the second item would look like:

``` bash
# Inside of `twolfson/gittip-badge`
# Update git remote
git remote rm origin
git remote add origin git@github.com:gratipay/grapitay-badge

# Push all branches
git push --all
```

The downside is that we are left maintaining legacy URLs due to hotlinks to the `master` URL.

```
https://rawgithub.com/twolfson/gittip-badge/master/dist/gittip.png
```

https://github.com/twolfson/foundry/blame/1.1.1/README.md#L123-L125

This means we must always maintain a `dist/gittip.png`, even after the rename. I _should_ have made another branch (e.g. `0.x.x`) and been linking to that but I am fallible and made a mistake.

**Comment by seanlinsley** [comment]
I don't think it's too much of a burden to maintain old URLs. Gratipay's main widgets (as well as [Shields](http://shields.io/)) are set up to respond to both old and new requests.

When moving & renaming a repo, GitHub maintains the URLs so people's existing links won't break.

**Comment by twolfson** [comment]
I was more concerned about it being dead weight in every `git commit` but if Gratipay doesn't mind/follows their convention, then I am fine with it. Can someone add me to the Gratipay organization so I can perform the rename?

**Comment by chadwhitacre** [comment]
@twolfson I've invited you to the Gratipay organization, owners group. I'll drop your perms back after you finish the repo transfer. :-)

**Comment by twolfson** [comment]
Sorry for the delay on this, renaming/updating repo now. For what it's worth, I think you can create another non-owners admin team that is allowed to create repos.

**Comment by twolfson** [comment]
Okay, transfer complete. I added it to the gratipay team when prompted. Feel free to update this to the proper teams.

It looks like the URLs are still working:

https://cdn.rawgit.com/twolfson/gittip-badge/1.1.0/dist/gratipay.png

https://rawgit.com/twolfson/gittip-badge/1.1.0/dist/gratipay.png

Next up is updating the documentation to match

**Comment by twolfson** [comment]
Okay, updated all references and decided to make another `major` release for good measure. Everything is up to date as of `2.0.0`

**Comment by rohitpaulk** [comment]
:+1:

**Comment by chadwhitacre** [comment]
Huzzah! I dropped you from the `owners` team before setting up a `Gratipay Badge` team with admin rights on this repo, so I believe you'll need to accept an invitation again?

**Comment by twolfson** [comment]
Yep, I did. Thanks =)

**Comment by chadwhitacre** [comment]
Huzzah! May I add you to https://gratipay.com/Gratipay/members/? :-)

**Comment by twolfson** [comment]
Yea, go for it. I thought I was already on there for my `www.gittip.com` contributions back in the day but I guess not =P

**Comment by chadwhitacre** [comment]
I just checked in the db. You _were_ on the team, but it looks like I dropped you during some housecleaning in April (we need better infrastructure to notify people of that, at the very least). Welcome back! :-)

**Comment by twolfson** [comment]
:tada:
